plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.16'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.lionproject24'
version = '0.0.1-SNAPSHOT'
description = 'fruit-shop'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'    // DB 연동
    implementation 'org.springframework.boot:spring-boot-starter-security'   // 로그인/인증
    implementation 'org.springframework.boot:spring-boot-starter-validation' // 입력값 검증
    implementation 'org.springframework.boot:spring-boot-starter-web'        // REST API

    compileOnly 'org.projectlombok:lombok'           // getter/setter 자동생성
    annotationProcessor 'org.projectlombok:lombok'

    runtimeOnly 'com.mysql:mysql-connector-j'   // MySQL 드라이버

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.17'  // Swagger 문서

    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'   // JWT 토큰
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


tasks.named('test') {
    useJUnitPlatform()
}
